# Generated by Django 6.0 on 2025-12-23 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tryout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('subjects', models.CharField(help_text='Pisahkan dengan · contoh: Matematika · Fisika · Kimia', max_length=255)),
                ('publish_time', models.DateTimeField()),
                ('work_time_minutes', models.PositiveIntegerField(help_text='Durasi ujian dalam menit')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['publish_time'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('school', models.CharField(max_length=200)),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Hari 1'), (2, 'Hari 2')], default=1)),
                ('blocked', models.BooleanField(default=False)),
                ('out_of_app_count', models.PositiveIntegerField(default=0)),
                ('raw_password', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantTryout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('out_of_app_count', models.PositiveIntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.participantprofile')),
                ('tryout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.tryout')),
            ],
            options={
                'unique_together': {('participant', 'tryout')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('tryout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.tryout')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('tryout', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ParticipantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('participant_tryout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.participanttryout')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
            options={
                'unique_together': {('participant_tryout', 'question')},
            },
        ),
    ]
