# Generated by Django 6.0 on 2025-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.FloatField(default=1.0),
        ),
    ]
