# Generated by Django 6.0 on 2025-12-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_question_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanttryout',
            name='max_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participanttryout',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
